### PR TITLE
allow base-compat-0.14

### PR DESCRIPTION
**Pull request by amigalemming**
as requested by Stackage

### CODE REVIEW

**Comment by phadej** [comment]
Please check https://github.com/phadej/topograph/blob/master/CONTRIBUTING.md

**Comment by amigalemming** [comment]
On Thu, 2 May 2024, Oleg Grenrus wrote:

> Please check https://github.com/phadej/topograph/blob/master/CONTRIBUTING.md

I could set you as maintainer in stackage/build-constraints.yaml, then you 
get the out-of-bounds warning directly.

**Comment by phadej** [comment]
I don't care about Stackage, sorry.

**Comment by amigalemming** [comment]
On Thu, 2 May 2024, Oleg Grenrus wrote:

> I don't care about Stackage, sorry.

Me too, but it saved me one level of indirection, when people started to 
send me build-depends relax requests.

**Comment by phadej** [comment]
> Me too, but it saved me one level of indirection, when people started to send me build-depends relax requests.

as CONTRIBUTING.md says I have my own process of figuring out dependency updates. I was already aware of `base-compat-0.14` release before this pull request, and I know which packages of mine depend on it.

I'm also aware that GHC-9.10 is to be released in a week, with `base-4.20` which I'd need to update bounds too as well. And I'm purposefully holding back on any maintenance tasks until then.

I don't want to do maintenance sweeps through all packages I maintain many times in a short time.

And to be clear, I don't need help maintaining packages. Version bumps is the easiest part of development process but still require quite a lot of trust. I'd rather welcome help with *difficult* issues.

**Pull request closed without merging**
